export const locationsArray = [
  { name: 'Kaitaia' },
  { name: 'Whangarei' },
  { name: 'Auckland' },
  { name: 'Tauranga' },
  { name: 'Hamilton' },
  { name: 'Rotorua' },
  { name: 'Gisborne' },
  { name: 'Taupo' },
  { name: 'New Plymouth' },
  { name: 'Napier' },
  { name: 'Whanganui' },
  { name: 'Palmerston North' },
  { name: 'Masterton' },
  { name: 'Wellington' },
  { name: 'Nelson' },
  { name: 'Taranaki' },
  { name: 'Blenheim' },
  { name: 'Westport' },
  { name: 'Kaikoura' },
  { name: 'Hokitika' },
  { name: 'Christchurch' },
  { name: 'Mt Cook' },
  { name: 'Lake Tekapo' },
  { name: 'Timaru' },
  { name: 'Milford Sound' },
  { name: 'Queenstown' },
  { name: 'Alexandra' },
  { name: 'Manapouri' },
  { name: 'Dunedin' },
  { name: 'Invercargill' },
  { name: 'Chatham Islands' },
]
